Repository EOussama/anusic-api, pull requests merged in 2020-11, with the labels that each got.

#6 Restructured the project
  go.mod
  src/enums/enum.media.go
  src/enums/enum.theme.go
  src/handlers/anime.go
  src/handlers/animeList.go
  src/handlers/index.go
  src/main.go
  src/models/anime.go
  src/models/theme.go
  src/utils/cache.go
  src/utils/env.go
  src/utils/scraper.go
Labels: dependencies, documentation, enhancement, good first issue

#14 React
  src/App.js
Labels: bug

#18 Create LICENSE
  LICENSE
Labels: documentation

#19 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation
